# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: risk_controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gogo_pb2 as gogo__pb2
import empty_pb2 as empty__pb2
import quote_data_pb2 as quote__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='risk_controller.proto',
  package='quote.service.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15risk_controller.proto\x12\x10quote.service.v1\x1a\ngogo.proto\x1a\x0b\x65mpty.proto\x1a\x10quote_data.proto\"_\n\x14MultiOrderStreamData\x12G\n\x06orders\x18\x01 \x03(\x0b\x32!.quote.service.v1.OrderStreamDataB\x14\xe2\xde\x1f\x06Orders\xea\xde\x1f\x06orders\"\xff\x01\n\x0fOrderStreamData\x12$\n\x06symbol\x18\x01 \x01(\tB\x14\xe2\xde\x1f\x06Symbol\xea\xde\x1f\x06symbol\x12!\n\x05price\x18\x02 \x01(\tB\x12\xe2\xde\x1f\x05Price\xea\xde\x1f\x05price\x12\x35\n\x0corder_amount\x18\x03 \x01(\x01\x42\x1f\xe2\xde\x1f\x0bOrderAmount\xea\xde\x1f\x0corder_amount\x12\x38\n\rhedged_amount\x18\x04 \x01(\x01\x42!\xe2\xde\x1f\x0cHedgedAmount\xea\xde\x1f\rhedged_amount\x12\x32\n\x04time\x18\x05 \x01(\x03\x42$\xe2\xde\x1f\x04Time\xea\xde\x1f\x04time\xfa\xde\x1f\x10wx/pkg/time.Time2\x88\x03\n\x0eRiskController\x12_\n\x18ServeMarketStream4Broker\x12\x16.google.protobuf.Empty\x1a\'.quote.service.v1.MultiMarketStreamData\"\x00\x30\x01\x12^\n\x17ServeMarketStream4Hedge\x12\x16.google.protobuf.Empty\x1a\'.quote.service.v1.MultiMarketStreamData\"\x00\x30\x01\x12_\n\x18ServeMarketStream4Client\x12\x16.google.protobuf.Empty\x1a\'.quote.service.v1.MultiMarketStreamData\"\x00\x30\x01\x12T\n\x0ePutOrderStream\x12&.quote.service.v1.MultiOrderStreamData\x1a\x16.google.protobuf.Empty\"\x00(\x01\x62\x06proto3'
  ,
  dependencies=[gogo__pb2.DESCRIPTOR,empty__pb2.DESCRIPTOR,quote__data__pb2.DESCRIPTOR,])




_MULTIORDERSTREAMDATA = _descriptor.Descriptor(
  name='MultiOrderStreamData',
  full_name='quote.service.v1.MultiOrderStreamData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='quote.service.v1.MultiOrderStreamData.orders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\006Orders\352\336\037\006orders', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=181,
)


_ORDERSTREAMDATA = _descriptor.Descriptor(
  name='OrderStreamData',
  full_name='quote.service.v1.OrderStreamData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='quote.service.v1.OrderStreamData.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\006Symbol\352\336\037\006symbol', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='quote.service.v1.OrderStreamData.price', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\005Price\352\336\037\005price', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_amount', full_name='quote.service.v1.OrderStreamData.order_amount', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\013OrderAmount\352\336\037\014order_amount', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hedged_amount', full_name='quote.service.v1.OrderStreamData.hedged_amount', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\014HedgedAmount\352\336\037\rhedged_amount', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='quote.service.v1.OrderStreamData.time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\004Time\352\336\037\004time\372\336\037\020wx/pkg/time.Time', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=439,
)

_MULTIORDERSTREAMDATA.fields_by_name['orders'].message_type = _ORDERSTREAMDATA
DESCRIPTOR.message_types_by_name['MultiOrderStreamData'] = _MULTIORDERSTREAMDATA
DESCRIPTOR.message_types_by_name['OrderStreamData'] = _ORDERSTREAMDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MultiOrderStreamData = _reflection.GeneratedProtocolMessageType('MultiOrderStreamData', (_message.Message,), {
  'DESCRIPTOR' : _MULTIORDERSTREAMDATA,
  '__module__' : 'risk_controller_pb2'
  # @@protoc_insertion_point(class_scope:quote.service.v1.MultiOrderStreamData)
  })
_sym_db.RegisterMessage(MultiOrderStreamData)

OrderStreamData = _reflection.GeneratedProtocolMessageType('OrderStreamData', (_message.Message,), {
  'DESCRIPTOR' : _ORDERSTREAMDATA,
  '__module__' : 'risk_controller_pb2'
  # @@protoc_insertion_point(class_scope:quote.service.v1.OrderStreamData)
  })
_sym_db.RegisterMessage(OrderStreamData)


_MULTIORDERSTREAMDATA.fields_by_name['orders']._options = None
_ORDERSTREAMDATA.fields_by_name['symbol']._options = None
_ORDERSTREAMDATA.fields_by_name['price']._options = None
_ORDERSTREAMDATA.fields_by_name['order_amount']._options = None
_ORDERSTREAMDATA.fields_by_name['hedged_amount']._options = None
_ORDERSTREAMDATA.fields_by_name['time']._options = None

_RISKCONTROLLER = _descriptor.ServiceDescriptor(
  name='RiskController',
  full_name='quote.service.v1.RiskController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=442,
  serialized_end=834,
  methods=[
  _descriptor.MethodDescriptor(
    name='ServeMarketStream4Broker',
    full_name='quote.service.v1.RiskController.ServeMarketStream4Broker',
    index=0,
    containing_service=None,
    input_type=empty__pb2._EMPTY,
    output_type=quote__data__pb2._MULTIMARKETSTREAMDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ServeMarketStream4Hedge',
    full_name='quote.service.v1.RiskController.ServeMarketStream4Hedge',
    index=1,
    containing_service=None,
    input_type=empty__pb2._EMPTY,
    output_type=quote__data__pb2._MULTIMARKETSTREAMDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ServeMarketStream4Client',
    full_name='quote.service.v1.RiskController.ServeMarketStream4Client',
    index=2,
    containing_service=None,
    input_type=empty__pb2._EMPTY,
    output_type=quote__data__pb2._MULTIMARKETSTREAMDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PutOrderStream',
    full_name='quote.service.v1.RiskController.PutOrderStream',
    index=3,
    containing_service=None,
    input_type=_MULTIORDERSTREAMDATA,
    output_type=empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RISKCONTROLLER)

DESCRIPTOR.services_by_name['RiskController'] = _RISKCONTROLLER

# @@protoc_insertion_point(module_scope)
