// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api.proto

#include "api.pb.h"
#include "api.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace trade {
namespace service {
namespace v1 {

static const char* Trade_method_names[] = {
  "/trade.service.v1.Trade/PutMarketStream",
};

std::unique_ptr< Trade::Stub> Trade::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Trade::Stub> stub(new Trade::Stub(channel));
  return stub;
}

Trade::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PutMarketStream_(Trade_method_names[0], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::trade::service::v1::MarketStreamData>* Trade::Stub::PutMarketStreamRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response) {
  return ::grpc_impl::internal::ClientWriterFactory< ::trade::service::v1::MarketStreamData>::Create(channel_.get(), rpcmethod_PutMarketStream_, context, response);
}

void Trade::Stub::experimental_async::PutMarketStream(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::experimental::ClientWriteReactor< ::trade::service::v1::MarketStreamData>* reactor) {
  ::grpc_impl::internal::ClientCallbackWriterFactory< ::trade::service::v1::MarketStreamData>::Create(stub_->channel_.get(), stub_->rpcmethod_PutMarketStream_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::trade::service::v1::MarketStreamData>* Trade::Stub::AsyncPutMarketStreamRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::trade::service::v1::MarketStreamData>::Create(channel_.get(), cq, rpcmethod_PutMarketStream_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::trade::service::v1::MarketStreamData>* Trade::Stub::PrepareAsyncPutMarketStreamRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::trade::service::v1::MarketStreamData>::Create(channel_.get(), cq, rpcmethod_PutMarketStream_, context, response, false, nullptr);
}

Trade::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Trade_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< Trade::Service, ::trade::service::v1::MarketStreamData, ::google::protobuf::Empty>(
          [](Trade::Service* service,
             ::grpc_impl::ServerContext* ctx,
             ::grpc_impl::ServerReader<::trade::service::v1::MarketStreamData>* reader,
             ::google::protobuf::Empty* resp) {
               return service->PutMarketStream(ctx, reader, resp);
             }, this)));
}

Trade::Service::~Service() {
}

::grpc::Status Trade::Service::PutMarketStream(::grpc::ServerContext* context, ::grpc::ServerReader< ::trade::service::v1::MarketStreamData>* reader, ::google::protobuf::Empty* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace trade
}  // namespace service
}  // namespace v1

