cmake_minimum_required(VERSION 3.7)
project(demo)

###############################################################################################
include_directories("../lib")
link_directories("../lib")
aux_source_directory(. DIR_SRCS)

###############################################################################################
add_executable(demo ${DIR_SRCS})
###############################################################################################