// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: stream_engine_server.proto

#include "stream_engine_server.pb.h"
#include "stream_engine_server.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace trade {
namespace service {
namespace v1 {

static const char* StreamEngineService_method_names[] = {
  "/trade.service.v1.StreamEngineService/GetQuote",
  "/trade.service.v1.StreamEngineService/SubscribeOneQuote",
  "/trade.service.v1.StreamEngineService/MultiSubscribeQuote",
  "/trade.service.v1.StreamEngineService/MultiSubscribeHedgeQuote",
  "/trade.service.v1.StreamEngineService/SetParams",
};

std::unique_ptr< StreamEngineService::Stub> StreamEngineService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StreamEngineService::Stub> stub(new StreamEngineService::Stub(channel));
  return stub;
}

StreamEngineService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetQuote_(StreamEngineService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SubscribeOneQuote_(StreamEngineService_method_names[1], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_MultiSubscribeQuote_(StreamEngineService_method_names[2], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_MultiSubscribeHedgeQuote_(StreamEngineService_method_names[3], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SetParams_(StreamEngineService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StreamEngineService::Stub::GetQuote(::grpc::ClientContext* context, const ::trade::service::v1::GetQuoteReq& request, ::trade::service::v1::QuoteData* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetQuote_, context, request, response);
}

void StreamEngineService::Stub::experimental_async::GetQuote(::grpc::ClientContext* context, const ::trade::service::v1::GetQuoteReq* request, ::trade::service::v1::QuoteData* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetQuote_, context, request, response, std::move(f));
}

void StreamEngineService::Stub::experimental_async::GetQuote(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::trade::service::v1::QuoteData* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetQuote_, context, request, response, std::move(f));
}

void StreamEngineService::Stub::experimental_async::GetQuote(::grpc::ClientContext* context, const ::trade::service::v1::GetQuoteReq* request, ::trade::service::v1::QuoteData* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetQuote_, context, request, response, reactor);
}

void StreamEngineService::Stub::experimental_async::GetQuote(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::trade::service::v1::QuoteData* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetQuote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::trade::service::v1::QuoteData>* StreamEngineService::Stub::AsyncGetQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::GetQuoteReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::trade::service::v1::QuoteData>::Create(channel_.get(), cq, rpcmethod_GetQuote_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::trade::service::v1::QuoteData>* StreamEngineService::Stub::PrepareAsyncGetQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::GetQuoteReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::trade::service::v1::QuoteData>::Create(channel_.get(), cq, rpcmethod_GetQuote_, context, request, false);
}

::grpc::ClientReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::SubscribeOneQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::GetQuoteReq& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), rpcmethod_SubscribeOneQuote_, context, request);
}

void StreamEngineService::Stub::experimental_async::SubscribeOneQuote(::grpc::ClientContext* context, ::trade::service::v1::GetQuoteReq* request, ::grpc::experimental::ClientReadReactor< ::trade::service::v1::MultiQuoteData>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeOneQuote_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::AsyncSubscribeOneQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::GetQuoteReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), cq, rpcmethod_SubscribeOneQuote_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::PrepareAsyncSubscribeOneQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::GetQuoteReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), cq, rpcmethod_SubscribeOneQuote_, context, request, false, nullptr);
}

::grpc::ClientReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::MultiSubscribeQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::SubscribeQuoteReq& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), rpcmethod_MultiSubscribeQuote_, context, request);
}

void StreamEngineService::Stub::experimental_async::MultiSubscribeQuote(::grpc::ClientContext* context, ::trade::service::v1::SubscribeQuoteReq* request, ::grpc::experimental::ClientReadReactor< ::trade::service::v1::MultiQuoteData>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(stub_->channel_.get(), stub_->rpcmethod_MultiSubscribeQuote_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::AsyncMultiSubscribeQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::SubscribeQuoteReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), cq, rpcmethod_MultiSubscribeQuote_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::PrepareAsyncMultiSubscribeQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::SubscribeQuoteReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), cq, rpcmethod_MultiSubscribeQuote_, context, request, false, nullptr);
}

::grpc::ClientReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::MultiSubscribeHedgeQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::SubscribeQuoteReq& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), rpcmethod_MultiSubscribeHedgeQuote_, context, request);
}

void StreamEngineService::Stub::experimental_async::MultiSubscribeHedgeQuote(::grpc::ClientContext* context, ::trade::service::v1::SubscribeQuoteReq* request, ::grpc::experimental::ClientReadReactor< ::trade::service::v1::MultiQuoteData>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(stub_->channel_.get(), stub_->rpcmethod_MultiSubscribeHedgeQuote_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::AsyncMultiSubscribeHedgeQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::SubscribeQuoteReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), cq, rpcmethod_MultiSubscribeHedgeQuote_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::trade::service::v1::MultiQuoteData>* StreamEngineService::Stub::PrepareAsyncMultiSubscribeHedgeQuoteRaw(::grpc::ClientContext* context, const ::trade::service::v1::SubscribeQuoteReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::trade::service::v1::MultiQuoteData>::Create(channel_.get(), cq, rpcmethod_MultiSubscribeHedgeQuote_, context, request, false, nullptr);
}

::grpc::Status StreamEngineService::Stub::SetParams(::grpc::ClientContext* context, const ::trade::service::v1::SetParamsReq& request, ::trade::service::v1::SetParamsResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetParams_, context, request, response);
}

void StreamEngineService::Stub::experimental_async::SetParams(::grpc::ClientContext* context, const ::trade::service::v1::SetParamsReq* request, ::trade::service::v1::SetParamsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetParams_, context, request, response, std::move(f));
}

void StreamEngineService::Stub::experimental_async::SetParams(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::trade::service::v1::SetParamsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetParams_, context, request, response, std::move(f));
}

void StreamEngineService::Stub::experimental_async::SetParams(::grpc::ClientContext* context, const ::trade::service::v1::SetParamsReq* request, ::trade::service::v1::SetParamsResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetParams_, context, request, response, reactor);
}

void StreamEngineService::Stub::experimental_async::SetParams(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::trade::service::v1::SetParamsResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetParams_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::trade::service::v1::SetParamsResp>* StreamEngineService::Stub::AsyncSetParamsRaw(::grpc::ClientContext* context, const ::trade::service::v1::SetParamsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::trade::service::v1::SetParamsResp>::Create(channel_.get(), cq, rpcmethod_SetParams_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::trade::service::v1::SetParamsResp>* StreamEngineService::Stub::PrepareAsyncSetParamsRaw(::grpc::ClientContext* context, const ::trade::service::v1::SetParamsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::trade::service::v1::SetParamsResp>::Create(channel_.get(), cq, rpcmethod_SetParams_, context, request, false);
}

StreamEngineService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamEngineService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamEngineService::Service, ::trade::service::v1::GetQuoteReq, ::trade::service::v1::QuoteData>(
          [](StreamEngineService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::trade::service::v1::GetQuoteReq* req,
             ::trade::service::v1::QuoteData* resp) {
               return service->GetQuote(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamEngineService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StreamEngineService::Service, ::trade::service::v1::GetQuoteReq, ::trade::service::v1::MultiQuoteData>(
          [](StreamEngineService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::trade::service::v1::GetQuoteReq* req,
             ::grpc_impl::ServerWriter<::trade::service::v1::MultiQuoteData>* writer) {
               return service->SubscribeOneQuote(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamEngineService_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StreamEngineService::Service, ::trade::service::v1::SubscribeQuoteReq, ::trade::service::v1::MultiQuoteData>(
          [](StreamEngineService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::trade::service::v1::SubscribeQuoteReq* req,
             ::grpc_impl::ServerWriter<::trade::service::v1::MultiQuoteData>* writer) {
               return service->MultiSubscribeQuote(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamEngineService_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StreamEngineService::Service, ::trade::service::v1::SubscribeQuoteReq, ::trade::service::v1::MultiQuoteData>(
          [](StreamEngineService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::trade::service::v1::SubscribeQuoteReq* req,
             ::grpc_impl::ServerWriter<::trade::service::v1::MultiQuoteData>* writer) {
               return service->MultiSubscribeHedgeQuote(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamEngineService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamEngineService::Service, ::trade::service::v1::SetParamsReq, ::trade::service::v1::SetParamsResp>(
          [](StreamEngineService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::trade::service::v1::SetParamsReq* req,
             ::trade::service::v1::SetParamsResp* resp) {
               return service->SetParams(ctx, req, resp);
             }, this)));
}

StreamEngineService::Service::~Service() {
}

::grpc::Status StreamEngineService::Service::GetQuote(::grpc::ServerContext* context, const ::trade::service::v1::GetQuoteReq* request, ::trade::service::v1::QuoteData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamEngineService::Service::SubscribeOneQuote(::grpc::ServerContext* context, const ::trade::service::v1::GetQuoteReq* request, ::grpc::ServerWriter< ::trade::service::v1::MultiQuoteData>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamEngineService::Service::MultiSubscribeQuote(::grpc::ServerContext* context, const ::trade::service::v1::SubscribeQuoteReq* request, ::grpc::ServerWriter< ::trade::service::v1::MultiQuoteData>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamEngineService::Service::MultiSubscribeHedgeQuote(::grpc::ServerContext* context, const ::trade::service::v1::SubscribeQuoteReq* request, ::grpc::ServerWriter< ::trade::service::v1::MultiQuoteData>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamEngineService::Service::SetParams(::grpc::ServerContext* context, const ::trade::service::v1::SetParamsReq* request, ::trade::service::v1::SetParamsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace trade
}  // namespace service
}  // namespace v1

